staging: removed part of code
drivers/staging/rtl8188eus/os_dep/linux/ioctl_cfg80211.c:1115:6: error:
      too many arguments to function call, expected 3, have 8
  ..., pmlmepriv->assoc_req + sizeof(struct rtw_ieee80211_hdr_3addr) + 2
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/net/cfg80211.h:5467:1: note:
      'cfg80211_roamed' declared here
void cfg80211_roamed(struct net_device *dev, struct cfg80211_roam_info *info,

(cherry picked from commit b9f023f4656715a461eb024923549fdb52ace6b2)
Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I8ed9d4349f4cc351958b9a41ffe378d920599097