Android.bp: Drop qti_kernel_headers
* It is already defined in the source.

Log:
error: kernel/oneplus/sm8350/Android.bp:31:1: module "qti_kernel_headers" already defined
       vendor/voltage/build/soong/Android.bp:58:1 <-- previous definition here
fatal errors encountered
09:55:54 soong bootstrap failed with: exit status 1

error: hardware/google/pixel/kernel_headers: MODULE.TARGET.HEADER_LIBRARIES.qti_kernel_headers.recovery already defined by...

Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I73506675e0a7d82fc91c7a8b0de3208665dd97ab
(cherry picked from commit 7f20acb1897c530a077aafc796e65a82194bd630)
Signed-off-by: Madara273 <ravenhoxs@gmail.com>